import type { MethodInfo } from './types.js';

/**
 * Generate file header with auto-generation warning
 */
function generateFileHeader(): string {
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was automatically generated by nuxt-openapi-hyperfetch.
 * Any manual changes will be overwritten on the next generation.
 *
 * @generated by nuxt-openapi-hyperfetch
 * @see https://github.com/dmartindiaz/nuxt-openapi-hyperfetch
 */

/* eslint-disable */
`;
}

/**
 * Options for code generation
 */
export interface GenerateOptions {
  baseUrl?: string;
}

/**
 * Generate a useFetch composable function
 */
export function generateComposableFile(
  method: MethodInfo,
  apiImportPath: string,
  options?: GenerateOptions
): string {
  const header = generateFileHeader();
  const imports = generateImports(method, apiImportPath);
  const functionBody = generateFunctionBody(method, options);

  return `${header}${imports}\n\n${functionBody}\n`;
}

/**
 * Extract base type names from a type string
 * Examples:
 *   Pet[] -> Pet
 *   Array<Pet> -> Pet
 *   Pet -> Pet
 *   { [key: string]: Pet } -> (empty, it's anonymous)
 */
function extractBaseTypes(type: string): string[] {
  if (!type) {
    return [];
  }

  // Handle array syntax: Pet[]
  const arrayMatch = type.match(/^(\w+)\[\]$/);
  if (arrayMatch) {
    return [arrayMatch[1]];
  }

  // Handle Array generic: Array<Pet>
  const arrayGenericMatch = type.match(/^Array<(\w+)>$/);
  if (arrayGenericMatch) {
    return [arrayGenericMatch[1]];
  }

  // If it's a simple named type (single word, PascalCase), include it
  if (/^[A-Z][a-zA-Z0-9]*$/.test(type)) {
    return [type];
  }

  // For complex types, don't extract anything
  return [];
}

/**
 * Generate import statements
 */
function generateImports(method: MethodInfo, apiImportPath: string): string {
  const typeNames = new Set<string>();

  // Extract base types from request type
  if (method.requestType) {
    const extracted = extractBaseTypes(method.requestType);
    extracted.forEach((t) => typeNames.add(t));
  }

  // Extract base types from response type
  if (method.responseType && method.responseType !== 'void') {
    const extracted = extractBaseTypes(method.responseType);
    extracted.forEach((t) => typeNames.add(t));
  }

  let imports = '';

  // Import types from API (only if we have named types to import)
  if (typeNames.size > 0) {
    imports += `import type { ${Array.from(typeNames).join(', ')} } from '${apiImportPath}';\n`;
  }

  // Import runtime helper
  imports += `import { useApiRequest, type ApiRequestOptions, type UseApiRequestReturn } from '../runtime/useApiRequest';`;

  // Vue imports needed by the generated function body
  const vueImports: string[] = [];
  if (method.requestType) {
    vueImports.push('shallowRef');
    vueImports.push('isRef');
  }
  if (method.hasBody || method.hasQueryParams || method.pathParams.length > 0) {
    vueImports.push('computed');
  }
  const vueTypeImports = method.requestType ? ['Ref', 'ComputedRef'] : [];
  const allVueImports = [
    ...vueImports,
    ...vueTypeImports.map((typeName) => `type ${typeName}`),
  ].join(', ');
  imports += `\nimport { ${allVueImports} } from 'vue';`;

  return imports;
}

/**
 * Generate the composable function body
 */
function generateFunctionBody(method: MethodInfo, options?: GenerateOptions): string {
  const hasParams = !!method.requestType;
  const responseType = method.responseType !== 'void' ? method.responseType : 'void';
  const optionsType = `ApiRequestOptions<${responseType}, DataT, PickT>`;
  const optionsArg = `options?: ${optionsType}`;

  const url = generateUrl(method);
  const fetchOptions = generateFetchOptions(method, options);

  const description = method.description ? `/**\n * ${method.description}\n */\n` : '';

  const pInit = hasParams ? `\n  const p = isRef(params) ? params : shallowRef(params)` : '';

  const genericTypeParams = `<
  DataT = ${responseType},
  PickT extends ReadonlyArray<string> | undefined = undefined
>`;

  const returnType = `UseApiRequestReturn<${responseType}, ${optionsType}>`;

  if (!hasParams) {
    return `${description}export function ${method.composableName}${genericTypeParams}(${optionsArg}): ${returnType}
export function ${method.composableName}${genericTypeParams}(${optionsArg}) {
  return useApiRequest<${responseType}, ${optionsType}>(${url}, ${fetchOptions})
}`;
  }

  const directParams = `params: ${method.requestType}`;
  const refParams = `params: Ref<${method.requestType}> | ComputedRef<${method.requestType}>`;

  return `${description}export function ${method.composableName}${genericTypeParams}(${directParams}, ${optionsArg}): ${returnType}
export function ${method.composableName}${genericTypeParams}(${refParams}, ${optionsArg}): ${returnType}
export function ${method.composableName}${genericTypeParams}(
  params: ${method.requestType} | Ref<${method.requestType}> | ComputedRef<${method.requestType}>,
  ${optionsArg}
): ${returnType} {${pInit}
  return useApiRequest<${responseType}, ${optionsType}>(${url}, ${fetchOptions})
}`;
}

/**
 * Generate URL (with path params if needed)
 */
function generateUrl(method: MethodInfo): string {
  if (method.pathParams.length === 0) {
    return `'${method.path}'`;
  }

  let url = method.path;
  for (const param of method.pathParams) {
    const accessor = `p.value.path.${param}`;
    url = url.replace(`{${param}}`, `\${${accessor}}`);
  }

  return `() => \`${url}\``;
}

/**
 * Generate fetch options object
 */
function generateFetchOptions(method: MethodInfo, generateOptions?: GenerateOptions): string {
  const options: string[] = [];

  // Method
  options.push(`method: '${method.httpMethod}'`);

  // Base URL (if provided in config)
  if (generateOptions?.baseUrl) {
    options.push(`baseURL: '${generateOptions.baseUrl}'`);
  }

  // Body
  if (method.hasBody) {
    options.push(`body: computed(() => p.value.body)`);
  }

  // Query params
  if (method.hasQueryParams) {
    options.push(`query: computed(() => p.value.query)`);
  }

  // Headers
  if (Object.keys(method.headers).length > 0) {
    const headersEntries = Object.entries(method.headers)
      .map(([key, value]) => `'${key}': '${value}'`)
      .join(',\n      ');
    options.push(`headers: {\n      ${headersEntries},\n      ...options?.headers\n    }`);
  }

  // Spread options
  options.push('...options');

  const optionsStr = options.join(',\n    ');
  return `{\n    ${optionsStr}\n  }`;
}

/**
 * Generate index.ts that exports all composables
 */
export function generateIndexFile(composableNames: string[]): string {
  const header = generateFileHeader();
  const exports = composableNames
    .map((name) => `export { ${name} } from './composables/${name}'`)
    .join('\n');

  return `${header}${exports}\n`;
}
