import { pascalCase, kebabCase } from 'change-case';
import type { ResourceInfo } from '../schema-analyzer/types.js';

// ─── File header ──────────────────────────────────────────────────────────────

function generateFileHeader(): string {
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was automatically generated by nuxt-openapi-generator.
 * Any manual changes will be overwritten on the next generation.
 *
 * @generated by nuxt-openapi-generator
 * @see https://github.com/dmartindiaz/nuxt-openapi-hyperfetch
 */

/* eslint-disable */
// @ts-nocheck
`;
}

// ─── Naming helpers ───────────────────────────────────────────────────────────

/**
 * operationId → useAsyncData composable name.
 * 'getPets' → 'useAsyncDataGetPets'
 */
function toAsyncDataName(operationId: string): string {
  return `useAsyncData${pascalCase(operationId)}`;
}

/**
 * composable name → kebab-case file name (without .ts).
 * 'useAsyncDataGetPets' → 'use-async-data-get-pets'
 */
function toFileName(composableName: string): string {
  return kebabCase(composableName);
}

// ─── Section builders ─────────────────────────────────────────────────────────

/**
 * Build all `import` lines for a resource connector.
 */
function buildImports(resource: ResourceInfo, composablesRelDir: string): string {
  const lines: string[] = [];

  // zod
  lines.push(`import { z } from 'zod';`);
  lines.push('');

  // runtime helpers (Nuxt alias — set up by the Nuxt module)
  const runtimeHelpers: string[] = [];
  if (resource.listEndpoint) {
    runtimeHelpers.push('useListConnector');
  }
  if (resource.detailEndpoint) {
    runtimeHelpers.push('useDetailConnector');
  }
  if (resource.createEndpoint || resource.updateEndpoint) {
    runtimeHelpers.push('useFormConnector');
  }
  if (resource.deleteEndpoint) {
    runtimeHelpers.push('useDeleteConnector');
  }

  for (const helper of runtimeHelpers) {
    lines.push(`import { ${helper} } from '#nxh/runtime/${helper}';`);
  }
  lines.push('');

  // generated useAsyncData composables
  const addImport = (operationId: string): void => {
    const name = toAsyncDataName(operationId);
    const file = toFileName(name);
    lines.push(`import { ${name} } from '${composablesRelDir}/${file}';`);
  };

  if (resource.listEndpoint) {
    addImport(resource.listEndpoint.operationId);
  }
  if (resource.detailEndpoint) {
    addImport(resource.detailEndpoint.operationId);
  }
  if (resource.createEndpoint) {
    addImport(resource.createEndpoint.operationId);
  }
  if (resource.updateEndpoint) {
    addImport(resource.updateEndpoint.operationId);
  }
  if (resource.deleteEndpoint) {
    addImport(resource.deleteEndpoint.operationId);
  }

  return lines.join('\n');
}

/**
 * Build Zod schema const declarations.
 */
function buildZodSchemas(resource: ResourceInfo): string {
  const lines: string[] = [];
  const pascal = pascalCase(resource.name);

  if (resource.zodSchemas.create) {
    lines.push(`const ${pascal}CreateSchema = ${resource.zodSchemas.create};`);
    lines.push('');
  }
  if (resource.zodSchemas.update) {
    lines.push(`const ${pascal}UpdateSchema = ${resource.zodSchemas.update};`);
    lines.push('');
  }

  // Derive TS types via z.infer
  if (resource.zodSchemas.create) {
    lines.push(`type ${pascal}CreateInput = z.infer<typeof ${pascal}CreateSchema>;`);
  }
  if (resource.zodSchemas.update) {
    lines.push(`type ${pascal}UpdateInput = z.infer<typeof ${pascal}UpdateSchema>;`);
  }

  return lines.join('\n');
}

/**
 * Build the body of the exported connector function.
 */
function buildFunctionBody(resource: ResourceInfo): string {
  const pascal = pascalCase(resource.name);
  const subConnectors: string[] = [];

  if (resource.listEndpoint) {
    const fn = toAsyncDataName(resource.listEndpoint.operationId);
    // paginated: true tells useListConnector to expose pagination helpers
    // (goToPage, nextPage, prevPage, setPerPage, pagination ref).
    // We set it whenever the spec declares a list endpoint that has a response schema,
    // which is a reliable proxy for "this API returns structured data worth paginating".
    const opts = resource.listEndpoint.responseSchema ? '{ paginated: true }' : '{}';
    subConnectors.push(`  const table = useListConnector(${fn}, ${opts});`);
  }

  if (resource.detailEndpoint) {
    const fn = toAsyncDataName(resource.detailEndpoint.operationId);
    subConnectors.push(`  const detail = useDetailConnector(${fn});`);
  }

  if (resource.createEndpoint) {
    const fn = toAsyncDataName(resource.createEndpoint.operationId);
    const schemaArg = resource.zodSchemas.create ? `{ schema: ${pascal}CreateSchema }` : '{}';
    subConnectors.push(`  const createForm = useFormConnector(${fn}, ${schemaArg});`);
  }

  if (resource.updateEndpoint) {
    const fn = toAsyncDataName(resource.updateEndpoint.operationId);
    const hasDetail = !!resource.detailEndpoint;

    // Build the options argument for useFormConnector:
    //   schema      → Zod schema for client-side validation before submission
    //   loadWith    → reference to the detail connector so the form auto-fills
    //                 when detail.item changes (user clicks "Edit" on a row)
    //
    // Four combinations are possible depending on what the spec provides:
    let schemaArg = '{}';
    if (resource.zodSchemas.update && hasDetail) {
      // Best case: validate AND pre-fill from detail
      schemaArg = `{ schema: ${pascal}UpdateSchema, loadWith: detail }`;
    } else if (resource.zodSchemas.update) {
      // Validate, but no detail endpoint to pre-fill from
      schemaArg = `{ schema: ${pascal}UpdateSchema }`;
    } else if (hasDetail) {
      // No Zod schema (no request body in spec), but still pre-fill from detail
      schemaArg = `{ loadWith: detail }`;
    }
    subConnectors.push(`  const updateForm = useFormConnector(${fn}, ${schemaArg});`);
  }

  if (resource.deleteEndpoint) {
    const fn = toAsyncDataName(resource.deleteEndpoint.operationId);
    subConnectors.push(`  const deleteAction = useDeleteConnector(${fn});`);
  }

  // Return object — only include what was built
  const returnKeys: string[] = [];
  if (resource.listEndpoint) {
    returnKeys.push('table');
  }
  if (resource.detailEndpoint) {
    returnKeys.push('detail');
  }
  if (resource.createEndpoint) {
    returnKeys.push('createForm');
  }
  if (resource.updateEndpoint) {
    returnKeys.push('updateForm');
  }
  if (resource.deleteEndpoint) {
    returnKeys.push('deleteAction');
  }

  const returnStatement = `  return { ${returnKeys.join(', ')} };`;

  return [
    `export function ${resource.composableName}() {`,
    ...subConnectors,
    returnStatement,
    `}`,
  ].join('\n');
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate the full source of a `use{Resource}Connector.ts` file.
 *
 * @param resource     ResourceInfo produced by Schema Analyzer
 * @param composablesRelDir  Relative path from the connector dir to the
 *                           useAsyncData composables dir (e.g. '../use-async-data')
 */
export function generateConnectorFile(resource: ResourceInfo, composablesRelDir: string): string {
  const header = generateFileHeader();
  const imports = buildImports(resource, composablesRelDir);
  const schemas = buildZodSchemas(resource);
  const fn = buildFunctionBody(resource);

  // Assemble file: header + imports + (optional) Zod blocks + function body.
  // Each section ends with its own trailing newline; join with \n adds one blank
  // line between sections, which matches Prettier's output for this structure.
  const parts: string[] = [header, imports];
  if (schemas.trim()) {
    parts.push(schemas);
  }
  parts.push(fn);

  return parts.join('\n') + '\n';
}

/**
 * Derive the output filename for a connector.
 * 'usePetsConnector' → 'use-pets-connector.ts'
 */
export function connectorFileName(composableName: string): string {
  return `${kebabCase(composableName)}.ts`;
}

/**
 * Generate an index barrel file that re-exports all connectors.
 */
export function generateConnectorIndexFile(composableNames: string[]): string {
  const header = generateFileHeader();
  const exports = composableNames
    .map((name) => `export { ${name} } from './${kebabCase(name)}';`)
    .join('\n');
  return `${header}${exports}\n`;
}
