import { pascalCase, kebabCase } from 'change-case';
import type { ResourceInfo } from '../schema-analyzer/types.js';

// ─── File header ──────────────────────────────────────────────────────────────

function generateFileHeader(): string {
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was automatically generated by nuxt-openapi-generator.
 * Any manual changes will be overwritten on the next generation.
 *
 * @generated by nuxt-openapi-generator
 * @see https://github.com/dmartindiaz/nuxt-openapi-hyperfetch
 */

/* eslint-disable */
`;
}

// ─── Naming helpers ───────────────────────────────────────────────────────────

/**
 * operationId → useAsyncData composable name.
 * 'getPets' → 'useAsyncDataGetPets'
 */
function toAsyncDataName(operationId: string): string {
  return `useAsyncData${pascalCase(operationId)}`;
}

/**
 * composable name → kebab-case file name (without .ts).
 * 'useAsyncDataGetPets' → 'use-async-data-get-pets'
 */
function toFileName(composableName: string): string {
  return composableName;
}

// ─── Section builders ─────────────────────────────────────────────────────────

/**
 * Build all `import` lines for a resource connector.
 */
function buildImports(
  resource: ResourceInfo,
  composablesRelDir: string,
  sdkRelDir: string,
  runtimeRelDir: string
): string {
  const lines: string[] = [];

  // vue — shallowRef needed when form, delete, or detail endpoints exist
  const needsShallowRef = !!(
    resource.createEndpoint ||
    resource.updateEndpoint ||
    resource.deleteEndpoint ||
    resource.detailEndpoint
  );
  const needsComputed = !!resource.detailEndpoint;
  if (needsShallowRef) {
    const vueImports = needsComputed ? `shallowRef, computed` : `shallowRef`;
    lines.push(`import { ${vueImports} } from 'vue';`);
    lines.push('');
  }

  // zod
  lines.push(`import { z } from 'zod';`);
  lines.push('');

  // connector-types — structural interfaces for return types
  const connectorTypeImports: string[] = ['ListConnectorReturn'];
  if (resource.detailEndpoint) {
    connectorTypeImports.push('DetailConnectorReturn');
  }
  if (resource.createEndpoint || resource.updateEndpoint) {
    connectorTypeImports.push('FormConnectorReturn');
  }
  if (resource.deleteEndpoint) {
    connectorTypeImports.push('DeleteConnectorReturn');
  }
  lines.push(
    `import type { ${connectorTypeImports.join(', ')} } from '${runtimeRelDir}/connector-types';`
  );
  lines.push('');

  // SDK request/response types (for the params overload signature)
  if (resource.listEndpoint) {
    const requestTypeName = `${pascalCase(resource.listEndpoint.operationId)}Request`;
    lines.push(`import type { ${requestTypeName} } from '${sdkRelDir}';`);
    lines.push('');
  }

  // runtime helpers — relative path works in both CLI and Nuxt module contexts
  // useListConnector is always imported to support the optional factory pattern
  const runtimeHelpers: string[] = ['useListConnector'];
  if (resource.detailEndpoint) {
    runtimeHelpers.push('useDetailConnector');
  }
  if (resource.createEndpoint || resource.updateEndpoint) {
    runtimeHelpers.push('useFormConnector');
  }
  if (resource.deleteEndpoint) {
    runtimeHelpers.push('useDeleteConnector');
  }

  for (const helper of runtimeHelpers) {
    lines.push(`import { ${helper} } from '${runtimeRelDir}/${helper}';`);
  }
  lines.push('');

  // generated useAsyncData composables
  const addImport = (operationId: string): void => {
    const name = toAsyncDataName(operationId);
    const file = toFileName(name);
    lines.push(`import { ${name} } from '${composablesRelDir}/${file}';`);
  };

  if (resource.listEndpoint) {
    addImport(resource.listEndpoint.operationId);
  }
  if (resource.detailEndpoint) {
    addImport(resource.detailEndpoint.operationId);
  }
  if (resource.createEndpoint) {
    addImport(resource.createEndpoint.operationId);
  }
  if (resource.updateEndpoint) {
    addImport(resource.updateEndpoint.operationId);
  }
  if (resource.deleteEndpoint) {
    addImport(resource.deleteEndpoint.operationId);
  }

  return lines.join('\n');
}

/**
 * Build Zod schema const declarations.
 */
function buildZodSchemas(resource: ResourceInfo): string {
  const lines: string[] = [];
  const pascal = pascalCase(resource.name);

  if (resource.zodSchemas.create) {
    lines.push(`const ${pascal}CreateSchema = ${resource.zodSchemas.create};`);
    lines.push('');
  }
  if (resource.zodSchemas.update) {
    lines.push(`const ${pascal}UpdateSchema = ${resource.zodSchemas.update};`);
    lines.push('');
  }

  // Derive TS types via z.infer
  if (resource.zodSchemas.create) {
    lines.push(`type ${pascal}CreateInput = z.infer<typeof ${pascal}CreateSchema>;`);
  }
  if (resource.zodSchemas.update) {
    lines.push(`type ${pascal}UpdateInput = z.infer<typeof ${pascal}UpdateSchema>;`);
  }

  return lines.join('\n');
}

/**
 * Build a const array with the column definitions inferred from the resource.
 * Returns an empty string if the resource has no columns.
 */
function buildColumns(resource: ResourceInfo): string {
  if (!resource.columns || resource.columns.length === 0) {
    return '';
  }
  const camel = resource.composableName
    .replace(/^use/, '')
    .replace(/Connector$/, '')
    .replace(/^./, (c) => c.toLowerCase());
  const varName = `${camel}Columns`;
  const entries = resource.columns
    .map((col) => `  { key: '${col.key}', label: '${col.label}', type: '${col.type}' }`)
    .join(',\n');
  return `const ${varName} = [\n${entries},\n];`;
}

/**
 * Build the TypeScript options interface for a connector.
 * Only includes fields relevant to the endpoints present on the resource.
 */
function buildOptionsInterface(resource: ResourceInfo): string {
  const typeName = `${pascalCase(resource.composableName)}Options`;
  const hasColumns = resource.columns && resource.columns.length > 0;
  const fields: string[] = [];

  if (resource.listEndpoint && hasColumns) {
    fields.push(`  columnLabels?: Record<string, string>;`);
    fields.push(`  columnLabel?: (key: string) => string;`);
  }
  if (resource.createEndpoint && resource.zodSchemas.create) {
    fields.push(`  createSchema?: z.ZodTypeAny | ((base: z.ZodTypeAny) => z.ZodTypeAny);`);
  }
  if (resource.updateEndpoint && resource.zodSchemas.update) {
    fields.push(`  updateSchema?: z.ZodTypeAny | ((base: z.ZodTypeAny) => z.ZodTypeAny);`);
  }
  if (resource.createEndpoint || resource.updateEndpoint || resource.deleteEndpoint) {
    fields.push(`  onRequest?: (ctx: any) => void | Promise<void>;`);
    fields.push(`  onSuccess?: (data: any) => void;`);
    fields.push(`  onError?: (err: any) => void;`);
    fields.push(`  onFinish?: () => void;`);
  }

  if (fields.length === 0) {
    return `type ${typeName} = Record<string, never>;`;
  }

  return [`interface ${typeName} {`, ...fields, `}`].join('\n');
}

/**
 * Build the TypeScript return type for a connector.
 */
function buildReturnType(resource: ResourceInfo): string {
  const pascal = pascalCase(resource.name);
  const typeName = `${pascalCase(resource.composableName)}Return`;
  const fields: string[] = [];

  // table is always present in the return type:
  //   - if listEndpoint exists → ListConnectorReturn<T> (always defined)
  //   - if no listEndpoint      → ListConnectorReturn<unknown> | undefined (only when factory passed)
  if (resource.listEndpoint) {
    fields.push(`  table: ListConnectorReturn<${pascal}>;`);
  } else {
    fields.push(`  table: ListConnectorReturn<unknown> | undefined;`);
  }

  if (resource.detailEndpoint) {
    fields.push(`  detail: DetailConnectorReturn<${pascal}>;`);
  }
  if (resource.createEndpoint) {
    const inputType = resource.zodSchemas.create
      ? `${pascal}CreateInput`
      : `Record<string, unknown>`;
    fields.push(`  createForm: FormConnectorReturn<${inputType}>;`);
  }
  if (resource.updateEndpoint) {
    const inputType = resource.zodSchemas.update
      ? `${pascal}UpdateInput`
      : `Record<string, unknown>`;
    fields.push(`  updateForm: FormConnectorReturn<${inputType}>;`);
  }
  if (resource.deleteEndpoint) {
    fields.push(`  deleteAction: DeleteConnectorReturn<${pascal}>;`);
  }

  return [`type ${typeName} = {`, ...fields, `};`].join('\n');
}

/**
 * Build the 3 generated lines for a composable that is keyed by a single path param
 * (detail, delete). Uses computed(() => ({ param: ref.value })) so that p.value is
 * always an object during setup — avoids `null.param` crash when Nuxt evaluates computedKey.
 */
function buildPathParamComposableLines(prefix: string, fn: string, pathParam: string): string[] {
  return [
    `  const ${prefix}Ref = shallowRef(null);`,
    `  const ${prefix}Composable = ${fn}(computed(() => ({ ${pathParam}: ${prefix}Ref.value })) as any, { immediate: false });`,
  ];
}

/**
 * Build the body of the exported connector function.
 */
function buildFunctionBody(resource: ResourceInfo): string {
  const pascal = pascalCase(resource.name);
  const hasColumns = resource.columns && resource.columns.length > 0;
  const camel = resource.composableName
    .replace(/^use/, '')
    .replace(/Connector$/, '')
    .replace(/^./, (c) => c.toLowerCase());
  const columnsVar = `${camel}Columns`;
  const subConnectors: string[] = [];

  // Derived type names — must match buildOptionsInterface / buildReturnType
  const optionsTypeName = `${pascalCase(resource.composableName)}Options`;
  const returnTypeName = `${pascalCase(resource.composableName)}Return`;

  // Destructure options param — only what's relevant for this resource
  const optionKeys: string[] = [];
  if (resource.listEndpoint && hasColumns) {
    optionKeys.push('columnLabels', 'columnLabel');
  }
  if (resource.createEndpoint && resource.zodSchemas.create) {
    optionKeys.push('createSchema');
  }
  if (resource.updateEndpoint && resource.zodSchemas.update) {
    optionKeys.push('updateSchema');
  }
  const hasMutations = !!(
    resource.createEndpoint ||
    resource.updateEndpoint ||
    resource.deleteEndpoint
  );
  if (hasMutations) {
    optionKeys.push('onRequest', 'onSuccess', 'onError', 'onFinish');
  }

  const optionsDestructure =
    optionKeys.length > 0 ? `  const { ${optionKeys.join(', ')} } = options;\n` : '';

  // ── List / table sub-connector ─────────────────────────────────────────────
  if (resource.listEndpoint) {
    const fn = toAsyncDataName(resource.listEndpoint.operationId);
    const listRequestTypeName = `${pascalCase(resource.listEndpoint.operationId)}Request`;
    const paginatedFlag = resource.listEndpoint.responseSchema ? 'paginated: true' : '';
    const columnsArg = hasColumns ? `columns: ${columnsVar}` : '';
    const labelArgs = hasColumns ? 'columnLabels, columnLabel' : '';
    const allArgs = [paginatedFlag, columnsArg, labelArgs].filter(Boolean).join(', ');
    const opts = allArgs ? `{ ${allArgs} }` : '{}';

    // Factory: if the first arg is a function the user provided their own composable;
    // otherwise build a default factory from the plain params object.
    subConnectors.push(
      `  const isFactory = typeof paramsOrSource === 'function';`,
      `  const listFactory = isFactory`,
      `    ? (paramsOrSource as () => unknown)`,
      `    : () => ${fn}((paramsOrSource ?? {}) as ${listRequestTypeName});`,
      `  const table = useListConnector(listFactory, ${opts}) as unknown as ListConnectorReturn<${pascal}>;`
    );
  } else {
    // No list endpoint — support optional factory for developer-provided list
    subConnectors.push(
      `  const table = paramsOrSource`,
      `    ? (useListConnector(paramsOrSource as () => unknown, {}) as unknown as ListConnectorReturn<unknown>)`,
      `    : undefined;`
    );
  }

  if (resource.detailEndpoint) {
    const fn = toAsyncDataName(resource.detailEndpoint.operationId);
    const pathParam = resource.detailEndpoint.pathParams[0] ?? 'id';
    subConnectors.push(...buildPathParamComposableLines('_detail', fn, pathParam));
    subConnectors.push(
      `  const detail = useDetailConnector((id: any) => { _detailRef.value = id; return _detailComposable; }) as unknown as DetailConnectorReturn<${pascal}>;`
    );
  }

  if (resource.createEndpoint) {
    const fn = toAsyncDataName(resource.createEndpoint.operationId);
    const inputType = resource.zodSchemas.create
      ? `${pascal}CreateInput`
      : `Record<string, unknown>`;
    const schemaArg = resource.zodSchemas.create
      ? `{ schema: ${pascal}CreateSchema, schemaOverride: createSchema }`
      : '{}';
    subConnectors.push(`  const _createRef = shallowRef({});`);
    subConnectors.push(
      `  const _createComposable = ${fn}(_createRef as any, { immediate: false, onRequest, onSuccess, onError, onFinish });`
    );
    subConnectors.push(
      `  const createForm = useFormConnector((p: any) => { _createRef.value = p; return _createComposable; }, ${schemaArg}) as unknown as FormConnectorReturn<${inputType}>;`
    );
  }

  if (resource.updateEndpoint) {
    const fn = toAsyncDataName(resource.updateEndpoint.operationId);
    const hasDetail = !!resource.detailEndpoint;
    const inputType = resource.zodSchemas.update
      ? `${pascal}UpdateInput`
      : `Record<string, unknown>`;

    let schemaArg = '{}';
    if (resource.zodSchemas.update && hasDetail) {
      schemaArg = `{ schema: ${pascal}UpdateSchema, schemaOverride: updateSchema, loadWith: detail }`;
    } else if (resource.zodSchemas.update) {
      schemaArg = `{ schema: ${pascal}UpdateSchema, schemaOverride: updateSchema }`;
    } else if (hasDetail) {
      schemaArg = `{ loadWith: detail }`;
    }
    subConnectors.push(`  const _updateRef = shallowRef({});`);
    subConnectors.push(
      `  const _updateComposable = ${fn}(_updateRef as any, { immediate: false, onRequest, onSuccess, onError, onFinish });`
    );
    subConnectors.push(
      `  const updateForm = useFormConnector((p: any) => { _updateRef.value = p; return _updateComposable; }, ${schemaArg}) as unknown as FormConnectorReturn<${inputType}>;`
    );
  }

  if (resource.deleteEndpoint) {
    const fn = toAsyncDataName(resource.deleteEndpoint.operationId);
    const pathParam = resource.deleteEndpoint.pathParams[0];
    if (pathParam) {
      subConnectors.push(...buildPathParamComposableLines('_delete', fn, pathParam));
      subConnectors.push(
        `  const _deleteComposableWithHooks = ${fn}(computed(() => ({ ${pathParam}: _deleteRef.value })) as any, { immediate: false, onRequest, onSuccess, onError, onFinish });`
      );
      subConnectors.push(
        `  const deleteAction = useDeleteConnector((item: any) => { _deleteRef.value = item?.${pathParam} ?? item?.id ?? item; return _deleteComposableWithHooks; }) as unknown as DeleteConnectorReturn<${pascal}>;`
      );
    } else {
      subConnectors.push(`  const _deleteRef = shallowRef({});`);
      subConnectors.push(
        `  const _deleteComposable = ${fn}(_deleteRef as any, { immediate: false, onRequest, onSuccess, onError, onFinish });`
      );
      subConnectors.push(
        `  const deleteAction = useDeleteConnector((p: any) => { _deleteRef.value = p; return _deleteComposable; }) as unknown as DeleteConnectorReturn<${pascal}>;`
      );
    }
  }

  // Return object — always includes table (undefined when no list + no factory)
  const returnKeys: string[] = ['table'];
  if (resource.detailEndpoint) {
    returnKeys.push('detail');
  }
  if (resource.createEndpoint) {
    returnKeys.push('createForm');
  }
  if (resource.updateEndpoint) {
    returnKeys.push('updateForm');
  }
  if (resource.deleteEndpoint) {
    returnKeys.push('deleteAction');
  }

  const returnStatement = `  return { ${returnKeys.join(', ')} } as ${returnTypeName};`;

  // ── Function signature ─────────────────────────────────────────────────────
  // Resources WITH a list endpoint: two overloads (factory | params).
  // Resources WITHOUT a list endpoint: single signature with optional factory.
  const lines: string[] = [];

  if (resource.listEndpoint) {
    const listRequestTypeName = `${pascalCase(resource.listEndpoint.operationId)}Request`;
    lines.push(
      `export function ${resource.composableName}(source: () => unknown, options?: ${optionsTypeName}): ${returnTypeName};`,
      `export function ${resource.composableName}(params?: ${listRequestTypeName}, options?: ${optionsTypeName}): ${returnTypeName};`,
      `export function ${resource.composableName}(paramsOrSource?: ${listRequestTypeName} | (() => unknown), options: ${optionsTypeName} = {}): ${returnTypeName} {`
    );
  } else {
    lines.push(
      `export function ${resource.composableName}(source?: () => unknown, options: ${optionsTypeName} = {}): ${returnTypeName} {`
    );
    // Alias so the body can use paramsOrSource uniformly
    lines.push(`  const paramsOrSource = source;`);
  }

  if (optionsDestructure.trim()) {
    lines.push(optionsDestructure.trimEnd());
  }
  lines.push(...subConnectors);
  lines.push(returnStatement);
  lines.push(`}`);

  return lines.join('\n');
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate the full source of a `use{Resource}Connector.ts` file.
 *
 * @param resource     ResourceInfo produced by Schema Analyzer
 * @param composablesRelDir  Relative path from the connector dir to the
 *                           useAsyncData composables dir (e.g. '../use-async-data')
 */
export function generateConnectorFile(
  resource: ResourceInfo,
  composablesRelDir: string,
  sdkRelDir = '../..',
  runtimeRelDir = '../../runtime'
): string {
  const header = generateFileHeader();
  const imports = buildImports(resource, composablesRelDir, sdkRelDir, runtimeRelDir);
  const schemas = buildZodSchemas(resource);
  const columns = buildColumns(resource);
  const optionsInterface = buildOptionsInterface(resource);
  const returnType = buildReturnType(resource);
  const fn = buildFunctionBody(resource);

  // Assemble file: header + imports + (optional) Zod blocks + columns const +
  // options interface + return type + function body.
  const parts: string[] = [header, imports];
  if (schemas.trim()) {
    parts.push(schemas);
  }
  if (columns.trim()) {
    parts.push(columns);
  }
  parts.push(optionsInterface);
  parts.push(returnType);
  parts.push(fn);

  return parts.join('\n') + '\n';
}

/**
 * Derive the output filename for a connector.
 * 'usePetsConnector' → 'use-pets-connector.ts'
 */
export function connectorFileName(composableName: string): string {
  return `${kebabCase(composableName)}.ts`;
}

/**
 * Generate an index barrel file that re-exports all connectors.
 */
export function generateConnectorIndexFile(composableNames: string[]): string {
  const header = generateFileHeader();
  const exports = composableNames
    .map((name) => `export { ${name} } from './${kebabCase(name)}';`)
    .join('\n');
  return `${header}${exports}\n`;
}
