import { pascalCase, kebabCase } from 'change-case';
import type { ResourceInfo } from '../components/schema-analyzer/types.js';

// â”€â”€â”€ File header â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function generateFileHeader(): string {
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was automatically generated by nuxt-openapi-generator.
 * Any manual changes will be overwritten on the next generation.
 *
 * @generated by nuxt-openapi-generator
 * @see https://github.com/dmartindiaz/nuxt-openapi-hyperfetch
 */

/* eslint-disable */
`;
}

// â”€â”€â”€ Naming helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function toAsyncDataName(operationId: string): string {
  return `useAsyncData${pascalCase(operationId)}`;
}

// â”€â”€â”€ URL builder â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/**
 * Convert an OpenAPI path template into a JS arrow function string.
 * '/pet/{petId}' + 'petId' â†’ '(id: string | number) => `/pet/${id}`'
 */
function buildUrlFn(path: string, pathParam?: string): string {
  if (!pathParam) {
    return `'${path}'`;
  }
  const urlTemplate = path.replace(`{${pathParam}}`, '${id}');
  return `(id: string | number) => \`${urlTemplate}\``;
}

// â”€â”€â”€ Section builders â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function buildImports(
  resource: ResourceInfo,
  composablesRelDir: string,
  sdkRelDir: string,
  runtimeRelDir: string
): string {
  const lines: string[] = [];

  // zod â€” always needed for schema declarations
  lines.push(`import { z } from 'zod';`);
  lines.push('');

  // connector-types â€” return type interfaces
  const typeImports: string[] = ['GetAllConnectorReturn'];
  if (resource.detailEndpoint) {
    typeImports.push('GetConnectorReturn');
  }
  if (resource.createEndpoint) {
    typeImports.push('CreateConnectorReturn');
  }
  if (resource.updateEndpoint) {
    typeImports.push('UpdateConnectorReturn');
  }
  if (resource.deleteEndpoint) {
    typeImports.push('DeleteConnectorReturn');
  }
  lines.push(`import type { ${typeImports.join(', ')} } from '${runtimeRelDir}/connector-types';`);
  lines.push('');

  // SDK model type -- import using the inferred item type name (from $ref) if available
  const modelTypeName = resource.itemTypeName;
  if (modelTypeName) {
    lines.push(`import type { ${modelTypeName} } from '${sdkRelDir}';`);
    lines.push('');
  }

  // SDK request type -- only when the list endpoint actually has query parameters
  if (resource.listEndpoint && resource.listEndpoint.hasQueryParams) {
    const requestTypeName = `${pascalCase(resource.listEndpoint.operationId)}Request`;
    lines.push(`import type { ${requestTypeName} } from '${sdkRelDir}';`);
    lines.push('');
  }

  // runtime connectors
  const runtimeImports: string[] = ['useGetAllConnector'];
  if (resource.detailEndpoint) {
    runtimeImports.push('useGetConnector');
  }
  if (resource.createEndpoint) {
    runtimeImports.push('useCreateConnector');
  }
  if (resource.updateEndpoint) {
    runtimeImports.push('useUpdateConnector');
  }
  if (resource.deleteEndpoint) {
    runtimeImports.push('useDeleteConnector');
  }

  for (const helper of runtimeImports) {
    lines.push(`import { ${helper} } from '${runtimeRelDir}/${helper}';`);
  }
  lines.push('');

  // useAsyncData composable â€” only needed for getAll (list endpoint)
  if (resource.listEndpoint) {
    const name = toAsyncDataName(resource.listEndpoint.operationId);
    lines.push(`import { ${name} } from '${composablesRelDir}/${name}';`);
    lines.push('');
  }

  return lines.join('\n');
}

function buildZodSchemas(resource: ResourceInfo): string {
  const lines: string[] = [];
  const pascal = pascalCase(resource.name);

  if (resource.zodSchemas.create) {
    lines.push(`const ${pascal}CreateSchema = ${resource.zodSchemas.create};`);
    lines.push('');
  }
  if (resource.zodSchemas.update) {
    lines.push(`const ${pascal}UpdateSchema = ${resource.zodSchemas.update};`);
    lines.push('');
  }
  if (resource.zodSchemas.create) {
    lines.push(`type ${pascal}CreateInput = z.infer<typeof ${pascal}CreateSchema>;`);
  }
  if (resource.zodSchemas.update) {
    lines.push(`type ${pascal}UpdateInput = z.infer<typeof ${pascal}UpdateSchema>;`);
  }

  return lines.join('\n');
}

function buildColumns(resource: ResourceInfo): string {
  if (!resource.columns || resource.columns.length === 0) {
    return '';
  }

  const camel = resource.composableName
    .replace(/^use/, '')
    .replace(/Connector$/, '')
    .replace(/^./, (c) => c.toLowerCase());
  const varName = `${camel}Columns`;
  const entries = resource.columns
    .map((col) => `  { key: '${col.key}', label: '${col.label}', type: '${col.type}' }`)
    .join(',\n');
  return `const ${varName} = [\n${entries},\n];`;
}

function buildFields(resource: ResourceInfo): string {
  const fields = resource.formFields?.create ?? resource.formFields?.update;
  if (!fields || fields.length === 0) {
    return '';
  }

  const camel = resource.composableName
    .replace(/^use/, '')
    .replace(/Connector$/, '')
    .replace(/^./, (c) => c.toLowerCase());
  const varName = `${camel}Fields`;
  const entries = fields
    .map((f) => {
      const opts = f.options
        ? `, options: [${f.options.map((o) => `{ label: '${o.label}', value: '${o.value}' }`).join(', ')}]`
        : '';
      return `  { key: '${f.key}', label: '${f.label}', type: '${f.type}', required: ${f.required}${opts} }`;
    })
    .join(',\n');
  return `const ${varName} = [\n${entries},\n];`;
}

function buildOptionsInterface(resource: ResourceInfo): string {
  const typeName = `${pascalCase(resource.composableName)}Options`;
  const hasColumns = resource.columns && resource.columns.length > 0;
  const fields: string[] = [];

  if (resource.listEndpoint && hasColumns) {
    fields.push(`  columnLabels?: Record<string, string>;`);
    fields.push(`  columnLabel?: (key: string) => string;`);
  }
  if (resource.createEndpoint && resource.zodSchemas.create) {
    const pascal = pascalCase(resource.name);
    fields.push(
      `  createSchema?: z.ZodTypeAny | ((base: typeof ${pascal}CreateSchema) => z.ZodTypeAny);`
    );
  }
  if (resource.updateEndpoint && resource.zodSchemas.update) {
    const pascal = pascalCase(resource.name);
    fields.push(
      `  updateSchema?: z.ZodTypeAny | ((base: typeof ${pascal}UpdateSchema) => z.ZodTypeAny);`
    );
  }
  if (resource.createEndpoint || resource.updateEndpoint || resource.deleteEndpoint) {
    fields.push(`  onRequest?: (ctx: any) => void | Promise<void> | Record<string, any>;`);
    fields.push(`  onSuccess?: (data: any, ctx: { operation: string }) => void;`);
    fields.push(`  onError?: (err: any, ctx: { operation: string }) => void;`);
    fields.push(`  onFinish?: (ctx: any) => void;`);
    fields.push(
      `  skipGlobalCallbacks?: boolean | Array<'onRequest' | 'onSuccess' | 'onError' | 'onFinish'>;`
    );
  }
  fields.push(`  baseURL?: string;`);

  if (fields.length === 1) {
    // only baseURL â€” minimal interface
    return [`interface ${typeName} {`, ...fields, `}`].join('\n');
  }
  return [`interface ${typeName} {`, ...fields, `}`].join('\n');
}

function buildReturnType(resource: ResourceInfo): string {
  const pascal = resource.itemTypeName ?? pascalCase(resource.name);
  const localPascal = pascalCase(resource.name);
  const typeName = `${pascalCase(resource.composableName)}Return`;
  const fields: string[] = [];

  fields.push(`  getAll: GetAllConnectorReturn<${pascal}>;`);
  if (resource.detailEndpoint) {
    fields.push(`  get: GetConnectorReturn<${pascal}>;`);
  }
  if (resource.createEndpoint) {
    const inputType = resource.zodSchemas.create
      ? `${localPascal}CreateInput`
      : `Record<string, unknown>`;
    fields.push(`  create: CreateConnectorReturn<${inputType}>;`);
  }
  if (resource.updateEndpoint) {
    const inputType = resource.zodSchemas.update
      ? `${localPascal}UpdateInput`
      : `Record<string, unknown>`;
    fields.push(`  update: UpdateConnectorReturn<${inputType}>;`);
  }
  if (resource.deleteEndpoint) {
    fields.push(`  del: DeleteConnectorReturn<${pascal}>;`);
  }

  return [`type ${typeName} = {`, ...fields, `};`].join('\n');
}

function buildFunctionBody(resource: ResourceInfo): string {
  const pascal = resource.itemTypeName ?? pascalCase(resource.name);
  const localPascal = pascalCase(resource.name);
  const hasColumns = resource.columns && resource.columns.length > 0;
  const hasFields = !!(resource.formFields?.create?.length || resource.formFields?.update?.length);
  const camel = resource.composableName
    .replace(/^use/, '')
    .replace(/Connector$/, '')
    .replace(/^./, (c) => c.toLowerCase());

  const columnsVar = `${camel}Columns`;
  const fieldsVar = `${camel}Fields`;
  const optionsTypeName = `${pascalCase(resource.composableName)}Options`;
  const returnTypeName = `${pascalCase(resource.composableName)}Return`;
  const hasMutations = !!(
    resource.createEndpoint ||
    resource.updateEndpoint ||
    resource.deleteEndpoint
  );

  // Options destructure
  const optionKeys: string[] = [];
  if (resource.listEndpoint && hasColumns) {
    optionKeys.push('columnLabels', 'columnLabel');
  }
  if (resource.createEndpoint && resource.zodSchemas.create) {
    optionKeys.push('createSchema');
  }
  if (resource.updateEndpoint && resource.zodSchemas.update) {
    optionKeys.push('updateSchema');
  }
  if (hasMutations) {
    optionKeys.push('onRequest', 'onSuccess', 'onError', 'onFinish', 'skipGlobalCallbacks');
  }
  optionKeys.push('baseURL');
  const optionsDestructure = `  const { ${optionKeys.join(', ')} } = options;\n`;

  const lines: string[] = [];

  // â”€â”€ Function signature â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.listEndpoint) {
    const hasQueryParams = resource.listEndpoint.hasQueryParams;
    const listRequestTypeName = hasQueryParams
      ? `${pascalCase(resource.listEndpoint.operationId)}Request`
      : `Record<string, never>`;
    lines.push(
      `export function ${resource.composableName}(source: () => unknown, options?: ${optionsTypeName}): ${returnTypeName};`,
      `export function ${resource.composableName}(params?: ${listRequestTypeName}, options?: ${optionsTypeName}): ${returnTypeName};`,
      `export function ${resource.composableName}(paramsOrSource?: ${listRequestTypeName} | (() => unknown), options: ${optionsTypeName} = {}): ${returnTypeName} {`
    );
  } else {
    lines.push(
      `export function ${resource.composableName}(options: ${optionsTypeName} = {}): ${returnTypeName} {`
    );
    lines.push(`  const paramsOrSource = undefined;`);
  }

  lines.push(optionsDestructure.trimEnd());
  lines.push('');

  // â”€â”€ getAll â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.listEndpoint) {
    const fn = toAsyncDataName(resource.listEndpoint.operationId);
    const hasQueryParams = resource.listEndpoint.hasQueryParams;
    const listRequestTypeName = hasQueryParams
      ? `${pascalCase(resource.listEndpoint.operationId)}Request`
      : `Record<string, never>`;
    const columnsArg = hasColumns ? `columns: ${columnsVar}` : '';
    const labelArgs = hasColumns ? 'columnLabels, columnLabel' : '';
    const allArgs = [columnsArg, labelArgs].filter(Boolean).join(', ');
    const opts = allArgs ? `{ ${allArgs} }` : '{}';

    lines.push(
      `  const isFactory = typeof paramsOrSource === 'function';`,
      `  const listFactory = isFactory`,
      `    ? (paramsOrSource as () => unknown)`,
      `    : () => ${fn}((paramsOrSource ?? {}) as ${listRequestTypeName});`,
      `  const getAll = useGetAllConnector(listFactory, ${opts}) as unknown as GetAllConnectorReturn<${pascal}>;`
    );
  } else {
    lines.push(
      `  const getAll = useGetAllConnector(() => ({}), {}) as unknown as GetAllConnectorReturn<${pascal}>;`
    );
  }
  lines.push('');

  // â”€â”€ get â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.detailEndpoint) {
    const pathParam = resource.detailEndpoint.pathParams[0] ?? 'id';
    const urlFn = buildUrlFn(resource.detailEndpoint.path, pathParam);
    const fieldsArg = hasFields ? `fields: ${fieldsVar}` : '';
    const args = [
      'baseURL',
      'onRequest',
      'onSuccess',
      'onError',
      'onFinish',
      'skipGlobalCallbacks',
      fieldsArg,
    ]
      .filter(Boolean)
      .join(', ');
    lines.push(
      `  const get = useGetConnector(${urlFn}, { ${args} }) as unknown as GetConnectorReturn<${pascal}>;`
    );
    lines.push('');
  }

  // â”€â”€ create â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.createEndpoint) {
    const inputType = resource.zodSchemas.create
      ? `${localPascal}CreateInput`
      : `Record<string, unknown>`;
    const schemaArg = resource.zodSchemas.create
      ? `schema: ${localPascal}CreateSchema, schemaOverride: createSchema,`
      : '';
    const fieldsArg = hasFields ? `fields: ${fieldsVar},` : '';
    const method = resource.createEndpoint.method;
    lines.push(
      `  const create = useCreateConnector('${resource.createEndpoint.path}', {`,
      `    method: '${method}',`,
      ...(schemaArg ? [`    ${schemaArg}`] : []),
      ...(fieldsArg ? [`    ${fieldsArg}`] : []),
      `    onRequest, onSuccess, onError, onFinish,`,
      `    baseURL, skipGlobalCallbacks,`,
      `  }) as unknown as CreateConnectorReturn<${inputType}>;`
    );
    lines.push('');
  }

  // â”€â”€ update â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.updateEndpoint) {
    const inputType = resource.zodSchemas.update
      ? `${localPascal}UpdateInput`
      : `Record<string, unknown>`;
    const pathParam = resource.updateEndpoint.pathParams[0]; // undefined when ID comes from body
    const urlFn = buildUrlFn(resource.updateEndpoint.path, pathParam);
    const schemaArg = resource.zodSchemas.update
      ? `schema: ${localPascal}UpdateSchema, schemaOverride: updateSchema,`
      : '';
    const fieldsArg = hasFields ? `fields: ${fieldsVar},` : '';
    const method = resource.updateEndpoint.method;
    lines.push(
      `  const update = useUpdateConnector(${urlFn}, {`,
      `    method: '${method}',`,
      ...(schemaArg ? [`    ${schemaArg}`] : []),
      ...(fieldsArg ? [`    ${fieldsArg}`] : []),
      `    onRequest, onSuccess, onError, onFinish,`,
      `    baseURL, skipGlobalCallbacks,`,
      `  }) as unknown as UpdateConnectorReturn<${inputType}>;`
    );
    lines.push('');
  }

  // â”€â”€ del â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  if (resource.deleteEndpoint) {
    const pathParam = resource.deleteEndpoint.pathParams[0];
    const urlFn = buildUrlFn(resource.deleteEndpoint.path, pathParam);
    // idFn: extract the ID from the staged item â€” try the path param name first, then .id
    const idFn = pathParam
      ? `(item: any) => item?.${pathParam} ?? item?.id ?? item`
      : `(item: any) => item?.id ?? item`;
    lines.push(
      `  const del = useDeleteConnector(`,
      `    ${idFn},`,
      `    ${urlFn},`,
      `    { onRequest, onSuccess, onError, onFinish, baseURL, skipGlobalCallbacks }`,
      `  ) as unknown as DeleteConnectorReturn<${pascal}>;`
    );
    lines.push('');
  }

  // â”€â”€ return â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const returnKeys: string[] = ['getAll'];
  if (resource.detailEndpoint) {
    returnKeys.push('get');
  }
  if (resource.createEndpoint) {
    returnKeys.push('create');
  }
  if (resource.updateEndpoint) {
    returnKeys.push('update');
  }
  if (resource.deleteEndpoint) {
    returnKeys.push('del');
  }

  lines.push(`  return { ${returnKeys.join(', ')} } as ${returnTypeName};`);
  lines.push(`}`);

  return lines.join('\n');
}

// â”€â”€â”€ Public API â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function generateConnectorFile(
  resource: ResourceInfo,
  composablesRelDir: string,
  sdkRelDir = '../..',
  runtimeRelDir = '../../runtime'
): string {
  const header = generateFileHeader();
  const imports = buildImports(resource, composablesRelDir, sdkRelDir, runtimeRelDir);
  const schemas = buildZodSchemas(resource);
  const columns = buildColumns(resource);
  const fields = buildFields(resource);
  const optionsInterface = buildOptionsInterface(resource);
  const returnType = buildReturnType(resource);
  const fn = buildFunctionBody(resource);

  const parts: string[] = [header, imports];
  if (schemas.trim()) {
    parts.push(schemas);
  }
  if (columns.trim()) {
    parts.push(columns);
  }
  if (fields.trim()) {
    parts.push(fields);
  }
  parts.push(optionsInterface);
  parts.push(returnType);
  parts.push(fn);

  return parts.join('\n') + '\n';
}

export function connectorFileName(composableName: string): string {
  return `${kebabCase(composableName)}.ts`;
}

export function generateConnectorIndexFile(composableNames: string[]): string {
  const header = generateFileHeader();
  const exports = composableNames
    .map((name) => `export { ${name} } from './${kebabCase(name)}';`)
    .join('\n');
  return `${header}${exports}\n`;
}
