import type { MethodInfo } from './types.js';

/**
 * Generate file header with auto-generation warning
 */
function generateFileHeader(): string {
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was automatically generated by nuxt-openapi-generator.
 * Any manual changes will be overwritten on the next generation.
 *
 * @generated by nuxt-openapi-generator
 * @see https://github.com/dmartindiaz/nuxt-openapi-hyperfetch
 */

/* eslint-disable */
// @ts-nocheck
`;
}

/**
 * Options for code generation
 */
export interface GenerateOptions {
  baseUrl?: string;
  backend?: string;
}

/**
 * Generate a useAsyncData composable function
 */
export function generateComposableFile(
  method: MethodInfo,
  apiImportPath: string,
  options?: GenerateOptions
): string {
  const header = generateFileHeader();
  const imports = generateImports(method, apiImportPath, false);
  const functionBody = generateFunctionBody(method, false, options);

  return `${header}${imports}\n\n${functionBody}\n`;
}

/**
 * Generate a useAsyncData composable function (Raw version with headers)
 */
export function generateRawComposableFile(
  method: MethodInfo,
  apiImportPath: string,
  options?: GenerateOptions
): string {
  const header = generateFileHeader();
  const imports = generateImports(method, apiImportPath, true);
  const functionBody = generateFunctionBody(method, true, options);

  return `${header}${imports}\n\n${functionBody}\n`;
}

/**
 * Extract base type names from a type string
 * Examples:
 *   Pet[] -> Pet
 *   Array<Pet> -> Pet
 *   Pet -> Pet
 *   { [key: string]: Pet } -> (empty, it's anonymous)
 */
function extractBaseTypes(type: string): string[] {
  if (!type) {
    return [];
  }

  // Handle array syntax: Pet[]
  const arrayMatch = type.match(/^(\w+)\[\]$/);
  if (arrayMatch) {
    return [arrayMatch[1]];
  }

  // Handle Array generic: Array<Pet>
  const arrayGenericMatch = type.match(/^Array<(\w+)>$/);
  if (arrayGenericMatch) {
    return [arrayGenericMatch[1]];
  }

  // If it's a simple named type (single word, PascalCase), include it
  if (/^[A-Z][a-zA-Z0-9]*$/.test(type)) {
    return [type];
  }

  // For complex types, don't extract anything
  return [];
}

/**
 * Generate import statements
 */
function generateImports(method: MethodInfo, apiImportPath: string, isRaw: boolean): string {
  const typeNames = new Set<string>();

  // Extract base types from request type
  if (method.requestType) {
    const extracted = extractBaseTypes(method.requestType);
    extracted.forEach((t) => typeNames.add(t));
  }

  // Extract base types from response type
  if (method.responseType && method.responseType !== 'void') {
    const extracted = extractBaseTypes(method.responseType);
    extracted.forEach((t) => typeNames.add(t));
  }

  let imports = '';

  // Import types from API (only if we have named types to import)
  if (typeNames.size > 0) {
    imports += `import type { ${Array.from(typeNames).join(', ')} } from '${apiImportPath}';\n`;
  }

  // Import runtime helper (normal or raw)
  if (isRaw) {
    imports += `import { useApiAsyncDataRaw, type ApiAsyncDataRawOptions, type RawResponse } from '../runtime/useApiAsyncDataRaw';`;
  } else {
    imports += `import { useApiAsyncData, type ApiAsyncDataOptions } from '../runtime/useApiAsyncData';`;
  }

  return imports;
}

/**
 * Generate the composable function body
 */
function generateFunctionBody(
  method: MethodInfo,
  isRaw: boolean,
  generateOptions?: GenerateOptions
): string {
  const hasParams = !!method.requestType;
  const paramsArg = hasParams ? `params: ${method.requestType}` : '';

  // Determine the options type based on isRaw
  const optionsType = isRaw
    ? `ApiAsyncDataRawOptions<${method.responseType}>`
    : `ApiAsyncDataOptions<${method.responseType}>`;
  const optionsArg = `options?: ${optionsType}`;
  const args = hasParams ? `${paramsArg}, ${optionsArg}` : optionsArg;

  // Determine the response type generic
  const responseTypeGeneric = method.responseType !== 'void' ? `<${method.responseType}>` : '';

  // Generate unique key for useAsyncData
  const composableName =
    isRaw && method.rawMethodName
      ? `useAsyncData${method.rawMethodName.replace(/Raw$/, '')}Raw`
      : method.composableName.replace(/^useFetch/, 'useAsyncData');

  const key = `'${composableName}'`;

  const url = generateUrl(method);
  const fetchOptions = generateFetchOptions(method, generateOptions);

  const description = method.description ? `/**\n * ${method.description}\n */\n` : '';

  // Choose the correct wrapper function
  const wrapperFunction = isRaw ? 'useApiAsyncDataRaw' : 'useApiAsyncData';

  const pInit = hasParams ? `\n  const p = shallowRef(params)` : '';

  return `${description}export const ${composableName} = (${args}) => {${pInit}
  return ${wrapperFunction}${responseTypeGeneric}(${key}, ${url}, ${fetchOptions})
}`;
}

/**
 * Generate URL (with path params if needed)
 */
function generateUrl(method: MethodInfo): string {
  if (method.pathParams.length === 0) {
    return `'${method.path}'`;
  }

  let url = method.path;
  for (const param of method.pathParams) {
    const accessor = method.paramsShape === 'nested' ? `p.value.path.${param}` : `p.value.${param}`;
    url = url.replace(`{${param}}`, `\${${accessor}}`);
  }

  return `() => \`${url}\``;
}

/**
 * Generate fetch options object
 */
function generateFetchOptions(method: MethodInfo, generateOptions?: GenerateOptions): string {
  const options: string[] = [];

  // Method
  options.push(`method: '${method.httpMethod}'`);

  // Base URL (if provided in config)
  if (generateOptions?.baseUrl) {
    options.push(`baseURL: '${generateOptions.baseUrl}'`);
  }

  // Body
  if (method.hasBody) {
    if (method.paramsShape === 'nested') {
      options.push(`body: computed(() => p.value.body)`);
    } else if (method.bodyField) {
      options.push(`body: computed(() => p.value.${method.bodyField})`);
    }
  }

  // Query params (renamed to 'params' for $fetch)
  if (method.hasQueryParams) {
    if (method.paramsShape === 'nested') {
      options.push(`params: computed(() => p.value.query)`);
    } else if (method.queryParams.length > 0) {
      const queryObj = method.queryParams
        .map((param) => `${param}: p.value.${param}`)
        .join(',\n      ');
      options.push(`params: computed(() => ({\n      ${queryObj}\n    }))`);
    }
  }

  // Headers
  if (Object.keys(method.headers).length > 0) {
    const headersEntries = Object.entries(method.headers)
      .map(([key, value]) => `'${key}': '${value}'`)
      .join(',\n      ');
    options.push(`headers: {\n      ${headersEntries},\n      ...options?.headers\n    }`);
  }

  // Spread options
  options.push('...options');

  const optionsStr = options.join(',\n    ');
  return `{\n    ${optionsStr}\n  }`;
}

/**
 * Generate index.ts that exports all composables
 */
export function generateIndexFile(composableNames: string[]): string {
  const header = generateFileHeader();
  const exports = composableNames
    .map((name) => `export { ${name} } from './composables/${name}'`)
    .join('\n');

  return `${header}${exports}\n`;
}
